name: 'Build restful PDF'

on:
  push:
  pull_request:

jobs:
  write-book:
    name: Build Restful PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pdflatex
        run: |
          sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: Link and Produce PDF
        run: |
          pdflatex restful.tex
          pdflatex restful.tex

      - name: Attach Output
        uses: actions/upload-artifact@v3
        with:
          name: restful-pdf
          path: ./restful.pdf